# Generated by hand for MVP
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledSocialPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("platform", models.CharField(choices=[("twitter", "Twitter")], default="twitter", max_length=32)),
                ("template_text", models.TextField()),
                ("rendered_text", models.TextField(blank=True, null=True)),
                ("scheduled_time", models.DateTimeField()),
                ("status", models.CharField(choices=[("pending", "Pending"), ("sent", "Sent"), ("failed", "Failed")], default="pending", max_length=32)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(on_delete=models.CASCADE, to="base.event"),
                ),
                (
                    "created_by",
                    models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, to="base.user"),
                ),
                (
                    "session",
                    models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, to="base.submission"),
                ),
            ],
        ),
    ]

