# Generated by Django 5.2.10 on 2026-01-29 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_talkquestion_variant'),
        ('base', '0009_event_private_testmode_and_more'),
    ]

    operations = [
    ]
